[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g., LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
prompt_playground = true

# Process and display HTML in messages. This can be a security risk
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Autoscroll new user messages at the top of the window
user_message_autoscroll = true

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

edit_profile = true

# 🚨 [수정] spontaneous_file_upload를 단일 섹션으로 통합
[features.spontaneous_file_upload]
enabled = true
# Define accepted file types using MIME types
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
# Sample rate of the audio
sample_rate = 24000

[features.mcp.sse]
enabled = true

[features.mcp.stdio]
enabled = true
# Only the executables in the allow list can be used for MCP stdio server.
allowed_executables = [ "npx", "uvx", "python", "docker"]

[UI]
# Name of the assistant.
name = "AGENTCHAT"

language = "ko"

layout = "wide"

default_sidebar_state = "open"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Specify a CSS file that can be used to customize the user interface.
custom_css = "/public/custom.css"

# Specify a JavaScript file that can be used to customize the user interface.
custom_js = "/public/custom.js"


[UI.theme]
default_font_family = "Inter, sans-serif"

[meta]
generated_by = "2.5.5"